/*
 * TO-DO list
 *
 * This is an example server for TO-DO list.  This is part of the collection of articles dedicated to the development of RESTful API. To know more visit the [repository](https://github.com/dandpz/restfulapi-howto) containing the code for these examples and more.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)

	sh := http.StripPrefix("/swaggerui/", http.FileServer(http.Dir("./swagger/swaggerui/")))
	router.PathPrefix("/swaggerui/").Handler(sh)

	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"CreateTodo",
		strings.ToUpper("Post"),
		"/v1/todo",
		CreateTodo,
	},

	Route{
		"DeleteTodoById",
		strings.ToUpper("Delete"),
		"/v1/todo/{todoId}",
		DeleteTodoById,
	},

	Route{
		"GetTodoById",
		strings.ToUpper("Get"),
		"/v1/todo/{todoId}",
		GetTodoById,
	},

	Route{
		"GetTodoList",
		strings.ToUpper("Get"),
		"/v1/todo",
		GetTodoList,
	},
}
